### ISSUE TITLE
/ error: Could not read from file       /src/directives/AnimateInView

### ISSUE THREAD

**Issue by kknono** [neeravp/vue3-animate-in-view#2]
I got an error  ：could not read from file     /src/directives/AnimateInView

**Comment by neeravp** [comment]
@kknono Did you import as 
`import { AnimateInViewDirective } from "@neeravp/vue-3-animate-in-view";`

Can't reproduce the error you are getting. If you could post more context as to how you are importing the directive which gives you the error - I can try and look into it.

**Comment by Emil9999** [comment]
Getting the same issue with both directive and component :/

This is how my main.ts looks:
 ```
import { createApp } from 'vue' 
import { AnimateInViewDirective } from "@neeravp/vue-3-animate-in-view"; 
import App from './App.vue'
import './index.css'
import router from "./router/index"

createApp(App).use(router).directive("animate-inview", AnimateInViewDirective).mount('#app')
```
Without using the directive anywhere I get the same as @kknono:
```
node_modules/@neeravp/vue-3-animate-in-view/dist/vue-3-animate-in-view.esm.js:1:35: error: Could not resolve "@/components/AnimateInView.vue" (mark it as external to exclude it from the bundle)
    1 │ import AnimateInViewComponent from '@/components/AnimateInView.vue';

 > node_modules/@neeravp/vue-3-animate-in-view/dist/vue-3-animate-in-view.esm.js:3:35: error: Could not resolve "@/directives/AnimateInView" (mark it as external to exclude it from the bundle)
    3 │ import AnimateInViewDirective from '@/directives/AnimateInView';
```

**Comment by JonHerbert** [comment]
Same here

`import { createApp } from "vue";
import App from "./App.vue";
import "./registerServiceWorker";
import router from "./router";
import store from "./store";

import { AnimateInViewDirective } from "@neeravp/vue-3-animate-in-view";`

`These dependencies were not found:

* @/components/AnimateInView.vue in ./node_modules/@neeravp/vue-3-animate-in-view/dist/vue-3-animate-in-view.esm.js
* @/directives/AnimateInView in ./node_modules/@neeravp/vue-3-animate-in-view/dist/vue-3-animate-in-view.esm.js`

**Comment by Murked** [comment]
I also have this problem. Any idea how to solve it?

**Comment by obj63mc** [comment]
Currently the esm build is broken on this, when trying to run locally and build rollup is returning 

    src/entry.esm.ts → dist/vue-3-animate-in-view.esm.js...
    (!) Unresolved dependencies
    https://rollupjs.org/guide/en/#warning-treating-module-as-external-dependency
    @/components/AnimateInView.vue (imported by src/entry.esm.ts)
    @/directives/AnimateInView (imported by src/entry.esm.ts

Because it can't be built properly the export isn't working as well.  Trying to figure out a solve for this

**Comment by obj63mc** [comment]
Submitted a pull request to fix the esm build which should resolve this issue
